### ISSUE TITLE
The application no longer works normally

### ISSUE THREAD

**Issue by Resistance3301** [MrIkso/KodikDownloader#1]
Hello, your application no longer works, probably due to changes on the kodik side. Version 1.4 cannot even perform a regular search, at the same time, version 1.3 is able to find the necessary anime, but cannot download them, the episodes are displayed, but when you click on them, the video quality selection window does not pop up. Please, if possible, solve the above problem, because your application worked well for a long time.

**Comment by MrIkso** [comment]
Okay, I'm working for this issue

**Comment by MrIkso** [comment]
Fixed on https://github.com/MrIkso/KodikDownloader/commit/6f89197aa4739a7da0815ee0e219b87545de72aa

**Comment by Resistance3301** [comment]
Thank you very much!  I would also like to see a separate “Settings” item, where you could set the option for automatic naming of downloaded series, where you could use tags such as {title}, {episode}, {quality}, {voice}, the current version of me  not satisfied, I would just like to set a mask of this type for the files "{episode} episode.mp4"
