### ISSUE TITLE
The application no longer works normally

### ISSUE THREAD

**Issue by Resistance3301** [MrIkso/KodikDownloader#2]
After a while, the application began to show the same error that was described earlier, that is, it is not possible to download anything due to the lack of a pop-up window for selecting video quality, probably again some changes on the Kodik side.

**Comment by Resistance3301** [comment]
The application does not install

**Comment by MrIkso** [comment]
Oh, im update apk, old release don't signed. Redownload apk

**Comment by Resistance3301** [comment]
I am very grateful to you for your responsiveness and quick resolution of problems that arise.
